services:
  redis-cache:
    image: redis:alpine
    restart: unless-stopped
    container_name: redis_cache
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 50
      start_period: 10s

  django-backend:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/server-entrypoint.sh
    container_name: django_backend_container
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      redis-cache:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
  
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/worker-entrypoint.sh
    container_name: celery_worker
    restart: unless-stopped
    depends_on:
      - redis-cache
      - django-backend
    develop:
      watch:
        - action: sync
          path: .
          target: /app