# Generated by Django 5.2.8 on 2025-11-20 13:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.TextField(unique=True)),
                ('ethics_status', models.TextField(null=True)),
                ('date_submitted', models.TextField(null=True)),
                ('date_registered', models.TextField(null=True)),
                ('date_last_updated', models.TextField(null=True)),
                ('public_title', models.TextField(null=True)),
                ('scientific_title', models.TextField(null=True)),
                ('secondary_id', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('universal_trial_number', models.TextField(null=True)),
                ('health_condition', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('condition_category', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('condition_code', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('study_type', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('intervention_code', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('comparator', models.TextField(null=True)),
                ('control_group', models.TextField(null=True)),
                ('primary_outcome', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('primary_assessment_method', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('primary_timepoint', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('secondary_outcome', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('secondary_assessment_method', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('secondary_timepoint', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('inclusion_criteria', models.TextField(null=True)),
                ('min_age', models.TextField(null=True)),
                ('max_age', models.TextField(null=True)),
                ('sex', models.TextField(null=True)),
                ('healthy_volunteers', models.TextField(null=True)),
                ('exclusion_criteria', models.TextField(null=True)),
                ('purpose', models.TextField(null=True)),
                ('intervention_allocation', models.TextField(null=True)),
                ('enrolling_procedure', models.TextField(null=True)),
                ('sequence_generation', models.TextField(null=True)),
                ('masking_blinding', models.TextField(null=True)),
                ('who_mask_blind', models.TextField(null=True)),
                ('intervention_assignment', models.TextField(null=True)),
                ('other_design_features', models.TextField(null=True)),
                ('phase', models.TextField(null=True)),
                ('endpoint_type', models.TextField(null=True)),
                ('statistical_methods', models.TextField(null=True)),
                ('recruitment_status', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('trial_page_url', models.TextField(null=True)),
            ],
        ),
    ]
