# Generated by Django 5.2.8 on 2025-12-14 12:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_trial_anzctrtrial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrialsStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct_id', models.TextField(unique=True)),
                ('last_update_post_date', models.TextField()),
                ('brief_title', models.TextField(null=True)),
                ('official_title', models.TextField()),
                ('organization', models.TextField(null=True)),
                ('overall_status', models.TextField(null=True)),
                ('start_date', models.TextField(null=True)),
                ('completion_date', models.TextField(null=True)),
                ('lead_sponsor', models.TextField(null=True)),
                ('collaborators', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('brief_summary', models.TextField(null=True)),
                ('detailed_description', models.TextField(null=True)),
                ('study_type', models.TextField(null=True)),
                ('conditions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('condition_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('phases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('target_duration', models.TextField(null=True)),
                ('allocation', models.TextField(null=True)),
                ('intervention_model', models.TextField(null=True)),
                ('intervention_model_description', models.TextField(null=True)),
                ('primary_purpose', models.TextField(null=True)),
                ('observational_model', models.TextField(null=True)),
                ('time_perspective', models.TextField(null=True)),
                ('masking', models.TextField(null=True)),
                ('masking_description', models.TextField(null=True)),
                ('who_masked', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('biospec_description', models.TextField(null=True)),
                ('biospec_retention', models.TextField(null=True)),
                ('enrollment_count', models.BigIntegerField(null=True)),
                ('enrollment_type', models.TextField(null=True)),
                ('intervention_type', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('intervention_name', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('intervention_description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('primary_outcome_measure', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('primary_outcome_description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('primary_outcome_timeframe', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('secondary_outcome_measure', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('secondary_outcome_description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('secondary_outcome_timeframe', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('other_outcome_measure', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('other_outcome_description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('other_outcome_timeframe', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('eligibility_criteria', models.TextField(null=True)),
                ('eligibility_healthy_volunteers', models.BooleanField(null=True)),
                ('eligibility_gender_based', models.BooleanField(null=True)),
                ('eligibility_sex', models.TextField(null=True)),
                ('eligibility_gender_description', models.TextField(null=True)),
                ('eligibility_minage', models.TextField(null=True)),
                ('eligibility_maxage', models.TextField(null=True)),
                ('eligibility_stdages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('eligibility_study_population', models.TextField(null=True)),
                ('eligibility_sampling_method', models.TextField(null=True)),
                ('central_contact_name', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('central_contact_email', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
            ],
        ),
    ]
