# Generated by Django 5.2.8 on 2026-01-04 08:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clinicaltrialsstudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.TextField(unique=True)),
                ('last_update_date', models.TextField()),
                ('source_table', models.TextField()),
                ('source_id', models.TextField()),
                ('brief_title', models.TextField(null=True)),
                ('scientific_title', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('study_type', models.TextField(null=True)),
                ('conditions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('purpose', models.TextField(null=True)),
                ('enrollment_procedure', models.TextField(null=True)),
                ('intervention_code', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('intervention_description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('primary_outcome_measure', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('primary_outcome_description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('primary_outcome_timeframe', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('secondary_outcome_measure', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('secondary_outcome_description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('secondary_outcome_timeframe', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('eligibility_criteria', models.TextField(null=True)),
                ('healthy_volunteers', models.BooleanField(null=True)),
                ('sex', models.TextField(null=True)),
                ('minage', models.TextField(null=True)),
                ('maxage', models.TextField(null=True)),
            ],
        ),
    ]
