# Generated by Django 5.2.8 on 2026-01-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gentrial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gentrial',
            name='source_id',
        ),
    ]
