# Generated by Django 5.2.8 on 2026-01-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_gentrial_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gentrial',
            name='healthy_volunteers',
            field=models.TextField(null=True),
        ),
    ]
