# Generated by Django 5.2.8 on 2026-01-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_gentrial_healthy_volunteers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gentrial',
            name='intervention_description',
            field=models.TextField(null=True),
        ),
    ]
