from django.contrib.postgres.fields import ArrayField
from django.db import models


# Create your models here.
class AnzctrTrial(models.Model):
    registration_number = models.TextField(unique=True)
    ethics_status = models.TextField(null=True)
    date_submitted = models.TextField(null=True)
    date_registered = models.TextField(null=True)
    date_last_updated = models.TextField(null=True)
    public_title = models.TextField(null=True)
    scientific_title = models.TextField(null=True)
    secondary_id = ArrayField(models.TextField(null=True), null=True)
    universal_trial_number = models.TextField(null=True)
    health_condition = ArrayField(models.TextField(null=True), null=True)
    condition_category = ArrayField(models.TextField(null=True), null=True)
    condition_code = ArrayField(models.TextField(null=True), null=True)
    study_type = models.TextField(null=True)
    description = models.TextField(null=True)
    intervention_code = ArrayField(models.TextField(null=True), null=True)
    comparator = models.TextField(null=True)
    control_group = models.TextField(null=True)
    primary_outcome = ArrayField(models.TextField(null=True), null=True)
    primary_assessment_method = ArrayField(models.TextField(null=True), null=True)
    primary_timepoint = ArrayField(models.TextField(null=True), null=True)
    secondary_outcome = ArrayField(models.TextField(null=True), null=True)
    secondary_assessment_method = ArrayField(models.TextField(null=True), null=True)
    secondary_timepoint = ArrayField(models.TextField(null=True), null=True)
    inclusion_criteria = models.TextField(null=True)
    min_age = models.TextField(null=True)
    max_age = models.TextField(null=True)
    sex = models.TextField(null=True)
    healthy_volunteers = models.TextField(null=True)
    exclusion_criteria = models.TextField(null=True)
    purpose = models.TextField(null=True)
    intervention_allocation = models.TextField(null=True)
    enrolling_procedure = models.TextField(null=True)
    sequence_generation = models.TextField(null=True)
    masking_blinding = models.TextField(null=True)
    who_mask_blind = models.TextField(null=True)
    intervention_assignment = models.TextField(null=True)
    other_design_features = models.TextField(null=True)
    phase = models.TextField(null=True)
    endpoint_type = models.TextField(null=True)
    statistical_methods = models.TextField(null=True)
    recruitment_status = models.TextField(null=True)
    summary = models.TextField(null=True)
    trial_page_url = models.TextField(null=True)

    def __str__(self) -> str:
        return self.registration_number
    

class ClinicalTrialsStudy(models.Model):
    nct_id = models.TextField(unique=True)
    last_update_post_date = models.TextField()
    brief_title = models.TextField(null=True)
    official_title = models.TextField()
    organization = models.TextField(null=True)
    overall_status = models.TextField(null=True)
    start_date = models.TextField(null=True)
    completion_date = models.TextField(null=True)
    lead_sponsor = models.TextField(null=True)
    collaborators = ArrayField(models.TextField(null=True), null=True)
    brief_summary = models.TextField(null=True)
    detailed_description = models.TextField(null=True)
    study_type = models.TextField(null=True)
    conditions = ArrayField(models.TextField(null=True), null=True)
    condition_keywords = ArrayField(models.TextField(null=True), null=True)
    phases = ArrayField(models.TextField(null=True), null=True)
    target_duration = models.TextField(null=True)
    allocation = models.TextField(null=True)
    intervention_model = models.TextField(null=True)
    intervention_model_description = models.TextField(null=True)
    primary_purpose = models.TextField(null=True)
    observational_model = models.TextField(null=True)
    time_perspective = models.TextField(null=True)
    masking = models.TextField(null=True)
    masking_description = models.TextField(null=True)
    who_masked = ArrayField(models.TextField(null=True), null=True)
    biospec_description = models.TextField(null=True)
    biospec_retention = models.TextField(null=True)
    enrollment_count = models.BigIntegerField(null=True)
    enrollment_type = models.TextField(null=True)
    intervention_type = ArrayField(models.TextField(null=True), null=True)
    intervention_name = ArrayField(models.TextField(null=True), null=True)
    intervention_description = ArrayField(models.TextField(null=True), null=True)
    primary_outcome_measure = ArrayField(models.TextField(null=True), null=True)
    primary_outcome_description = ArrayField(models.TextField(null=True), null=True)
    primary_outcome_timeframe = ArrayField(models.TextField(null=True), null=True)
    secondary_outcome_measure = ArrayField(models.TextField(null=True), null=True)
    secondary_outcome_description = ArrayField(models.TextField(null=True), null=True)
    secondary_outcome_timeframe = ArrayField(models.TextField(null=True), null=True)
    other_outcome_measure = ArrayField(models.TextField(null=True), null=True)
    other_outcome_description = ArrayField(models.TextField(null=True), null=True)
    other_outcome_timeframe = ArrayField(models.TextField(null=True), null=True)
    eligibility_criteria = models.TextField(null=True)
    eligibility_healthy_volunteers = models.BooleanField(null=True)
    eligibility_gender_based = models.BooleanField(null=True)
    eligibility_sex = models.TextField(null=True)
    eligibility_gender_description = models.TextField(null=True)
    eligibility_minage = models.TextField(null=True)
    eligibility_maxage = models.TextField(null=True)
    eligibility_stdages = ArrayField(models.TextField(null=True), null=True)
    eligibility_study_population = models.TextField(null=True)
    eligibility_sampling_method = models.TextField(null=True)
    central_contact_name = ArrayField(models.TextField(null=True), null=True)
    central_contact_email = ArrayField(models.TextField(null=True), null=True)

    def __str__(self) -> str:
        return self.nct_id
    

class GenTrial(models.Model):
    tid = models.TextField(unique=True)
    last_update_date = models.TextField()
    source_table = models.TextField()
    brief_title = models.TextField(null=True)
    scientific_title = models.TextField(null=True)
    status = models.TextField(null=True)
    summary = models.TextField(null=True)
    description = models.TextField(null=True)
    study_type = models.TextField(null=True)
    conditions = ArrayField(models.TextField(null=True), null=True)
    purpose = models.TextField(null=True)
    enrollment_procedure = models.TextField(null=True)
    intervention_code = ArrayField(models.TextField(null=True), null=True)
    intervention_description = models.TextField(null=True)
    primary_outcome_measure = ArrayField(models.TextField(null=True), null=True)
    primary_outcome_description = ArrayField(models.TextField(null=True), null=True)
    primary_outcome_timeframe = ArrayField(models.TextField(null=True), null=True)
    secondary_outcome_measure = ArrayField(models.TextField(null=True), null=True)
    secondary_outcome_description = ArrayField(models.TextField(null=True), null=True)
    secondary_outcome_timeframe = ArrayField(models.TextField(null=True), null=True)
    eligibility_criteria = models.TextField(null=True)
    healthy_volunteers = models.TextField(null=True)
    sex = models.TextField(null=True)
    minage = models.TextField(null=True)
    maxage = models.TextField(null=True)

    def __str__(self) -> str:
        return self.tid