from django.contrib.postgres.fields import ArrayField
from django.db import models


# Create your models here.
class AnzctrTrial(models.Model):
    registration_number = models.TextField(unique=True)
    ethics_status = models.TextField(null=True)
    date_submitted = models.TextField(null=True)
    date_registered = models.TextField(null=True)
    date_last_updated = models.TextField(null=True)
    public_title = models.TextField(null=True)
    scientific_title = models.TextField(null=True)
    secondary_id = ArrayField(models.TextField(null=True), null=True)
    universal_trial_number = models.TextField(null=True)
    health_condition = ArrayField(models.TextField(null=True), null=True)
    condition_category = ArrayField(models.TextField(null=True), null=True)
    condition_code = ArrayField(models.TextField(null=True), null=True)
    study_type = models.TextField(null=True)
    description = models.TextField(null=True)
    intervention_code = ArrayField(models.TextField(null=True), null=True)
    comparator = models.TextField(null=True)
    control_group = models.TextField(null=True)
    primary_outcome = ArrayField(models.TextField(null=True), null=True)
    primary_assessment_method = ArrayField(models.TextField(null=True), null=True)
    primary_timepoint = ArrayField(models.TextField(null=True), null=True)
    secondary_outcome = ArrayField(models.TextField(null=True), null=True)
    secondary_assessment_method = ArrayField(models.TextField(null=True), null=True)
    secondary_timepoint = ArrayField(models.TextField(null=True), null=True)
    inclusion_criteria = models.TextField(null=True)
    min_age = models.TextField(null=True)
    max_age = models.TextField(null=True)
    sex = models.TextField(null=True)
    healthy_volunteers = models.TextField(null=True)
    exclusion_criteria = models.TextField(null=True)
    purpose = models.TextField(null=True)
    intervention_allocation = models.TextField(null=True)
    enrolling_procedure = models.TextField(null=True)
    sequence_generation = models.TextField(null=True)
    masking_blinding = models.TextField(null=True)
    who_mask_blind = models.TextField(null=True)
    intervention_assignment = models.TextField(null=True)
    other_design_features = models.TextField(null=True)
    phase = models.TextField(null=True)
    endpoint_type = models.TextField(null=True)
    statistical_methods = models.TextField(null=True)
    recruitment_status = models.TextField(null=True)
    summary = models.TextField(null=True)
    trial_page_url = models.TextField(null=True)

    def __str__(self) -> str:
        return self.registration_number